#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class RelativePanel;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}
namespace Microsoft {
    namespace Graphics {
        namespace Canvas {
            namespace UI {
                namespace Xaml {
                    ref class CanvasControl;
                }
            }
        }
    }
}

namespace Skattjakt
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ mainpanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ rubrik;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ infobuttonpanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ infoblock;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ player1info;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ palyer2info;
        private: ::Windows::UI::Xaml::Controls::Button^ nextbutton;
        private: ::Windows::UI::Xaml::Controls::Button^ next10button;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ player2block;
        private: ::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ p2image;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ player1block;
        private: ::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ p1image;
        private: ::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl^ canvas;
    };
}

